name: Fetch Senseering Data

on:
  workflow_dispatch: # Startet manuell per Klick

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Alle PropertyIDs auslesen
        env:
          AUTH_HEADER: ${{ secrets.AUTH_HEADER }}
        run: |
          curl --request GET \
            --url https://data-core.udp.senseering.io/api/elements/6 \
            --header 'Accept: application/json' \
            --header "Authorization: $AUTH_HEADER" \
            --header 'Content-Type: application/json' \
            --output live_data.json

      - name: Datei im Repository aktualisieren
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add live_data.json
          git commit -m "Fetch Element 6 Properties" || exit 0
          git push
